global:
  scrape_interval: 60s # Default global scrape interval.

scrape_configs:
  - job_name: 'snapvault-api'

    # Override the global default and scrape targets from this job every 15 seconds.
    scrape_interval: 15s

    # Endpoint of the monitored service (default: target/metrics)
    static_configs:
      - targets: [ '127.0.0.1:4000' ]
